build script and README updated

diff --git a/doit b/doit
--- a/doit
+++ b/doit
@@ -1,7 +1,26 @@
 #!/bin/bash
 
-DEST=~/x/xscreensaver-5.32
+VERSION="5.32"
+URL="http://www.jwz.org/xscreensaver/xscreensaver-${VERSION}.tar.gz"
+DEST="${HOME}/xscreensaver-${VERSION}-build"
+mkdir -p $DEST
+pushd $DEST
+if [ ! -f "xscreensaver-${VERSION}.tar.gz" ]; then
+    if [ -x /usr/bin/wget ]; then
+        wget $URL
+    elif [ -x /usr/bin/curl ]; then
+        curl -o "xscreensaver-${VERSION}.tar.gz" $URL
+    else
+        echo "need to download source but can't..."
+        exit 1
+    fi
+fi
+if [ ! -d "xscreensaver-${VERSION}" ]; then
+    tar xfz "xscreensaver-${VERSION}.tar.gz"
+fi
+popd
 #./shape_to_h  > commander.h
+DEST=${DEST}/xscreensaver-${VERSION}
 cp commander.{c,h,man} $DEST/hacks/glx
 cp commander.xml $DEST/hacks/config
 patch $DEST/hacks/glx/Makefile.in < Makefile.in.diff
@@ -9,3 +28,9 @@ cd $DEST
 touch config.h
 ./configure
 make
+echo ""
+if [ -x ${DEST}/hacks/glx/commander ]; then
+    echo built: ${DEST}/hacks/glx/commander
+else
+    echo build failed... sorry
+fi
